### ISSUE TITLE
Add new language: basque

### ISSUE THREAD

**Issue by erral** [stefangabos/world_countries#38]
Hi:

This project has been very useful for us to get the translations of the country names for a project.

Can you please add basque (eu) translations? The [wikipedia page](https://eu.wikipedia.org/wiki/ISO_3166-1#Kodeen_taula) is up to date with official basque names, and if someone is missing I will update it right away:

**Comment by stefangabos** [comment]
Just found out very interesting stuff about the basque language!

Here's the stuff that's not ok

```
Curaçao, cw, 531, cuw
Saint Barthélemy, bl, 652, blm
Saint Martin (French part), mf, 663, maf
Sint Maarten (Dutch part), sx, 534, sxm
Svalbard and Jan Mayen, sj, 744, sjm
```

**Comment by erral** [comment]
I added those to the table. The wikipedia page for Svalbard and Jan Mayen is missing, but I will create it later today or tomorrow. I hope that it's not an obstacle to run your script.

**Comment by stefangabos** [comment]
No, those pages aren't required - just the entries on the ISO 3166 page

**Comment by stefangabos** [comment]
there's an error on the page - look for Txantiloi:Herrialde info Svalbard eta Jan Mayen

**Comment by erral** [comment]
Yep, we have just fixed the error and now the table should be completed.

**Comment by stefangabos** [comment]
Almost there.
Looking in the [history](https://eu.wikipedia.org/w/index.php?title=ISO_3166-1&diff=8155981&oldid=8155980), i think you accidentally removed `[Saint Kitts and Nevis, kn, 659, kna]`. 
And still missing is `[Bonaire, Sint Eustatius and Saba, bq, 535, bes]` - I don't know why my script didn't show this to me the first time
Thanks!

**Comment by erral** [comment]
I restored Saint Kittis and added Bonaire :)

**Comment by stefangabos** [comment]
Done!
Note that `Belgika` and `Belize` are present twice, once at the bottom of the page
Thanks a lot for your help!

**Comment by erral** [comment]
I wonder why we had that on Wikipedia....

I fixed that, anyway. Thanks!

**Comment by erral** [comment]
Just one more thing, I have seen that you have added basque language with the "es-pv" code. I think that that's the code for the Basque region in Spain and not the code for the language, which is "eu". Can you check it?

**Comment by stefangabos** [comment]
It is the ISO 3166 code

**Comment by erral** [comment]
Yes but "basque" is a language and not a subdivision, right? It should be a ISO-639-1 code shouldn't it?

**Comment by stefangabos** [comment]
you are right. i am not at my desk but will be in an hour or so and i will
fix it

**Comment by stefangabos** [comment]
Should be good now

**Comment by erral** [comment]
Indeed. Thanks!!!

**Comment by stefangabos** [comment]
Thank you!
